spring.data.mongodb.uri=mongodb+srv://kevinlobo998_db_user:0FsGGbTl8iiANLa9@cluster0.8lq2t7p.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.security=DEBUG